### ISSUE TITLE
Error when using higher OTEL Version

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-tracing#209]
### Expected Behavior

To work properly

### Actual Behaviour

```
io.micronaut.context.exceptions.ConfigurationException: Exception thrown instantiating MicronautLambdaRuntimeHandler
--
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.createRequestHandler(MicronautLambdaRuntime.java:40)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.createHandler(AbstractMicronautLambdaRuntime.java:200)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:321)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:137)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:50)
Caused by: com.amazonaws.serverless.exceptions.ContainerInitializationException: Error starting Micronaut container: Bean definition [io.micronaut.tracing.opentelemetry.interceptor.ContinueSpanOpenTelemetryTraceInterceptor] could not be loaded: io.opentelemetry.instrumentation.api.util.ClassAndMethod
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.initialize(MicronautLambdaContainerHandler.java:260)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:193)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:146)
at io.micronaut.function.aws.proxy.MicronautLambdaHandler.<init>(MicronautLambdaHandler.java:54)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.createRequestHandler(MicronautLambdaRuntime.java:38)
... 4 more
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.tracing.opentelemetry.interceptor.ContinueSpanOpenTelemetryTraceInterceptor] could not be loaded: io.opentelemetry.instrumentation.api.util.ClassAndMethod
at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1907)
at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249)
at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.initialize(MicronautLambdaContainerHandler.java:256)
... 8 more
Caused by: java.lang.NoClassDefFoundError: io.opentelemetry.instrumentation.api.util.ClassAndMethod
at io.micronaut.tracing.opentelemetry.interceptor.$ContinueSpanOpenTelemetryTraceInterceptor$Definition.<clinit>(Unknown Source)
at io.micronaut.tracing.opentelemetry.interceptor.$ContinueSpanOpenTelemetryTraceInterceptor$Definition$Reference.load(Unknown Source)
at io.micronaut.context.AbstractInitializableBeanDefinitionReference.load(AbstractInitializableBeanDefinitionReference.java:145)
at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2724)
at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1905)
... 14 more
```

### Steps To Reproduce

Add the following to dependencies:

```
val otelAlphaVersion = "1.18.0-alpha"
val otelVersion = "1.18.0"

dependencies {
    implementation(enforcedPlatform("io.opentelemetry:opentelemetry-bom:$otelVersion"))
    implementation(enforcedPlatform("io.opentelemetry:opentelemetry-bom-alpha:$otelAlphaVersion"))

    constraints {
        implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:$otelAlphaVersion")
        implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-semconv:$otelAlphaVersion")
        implementation("io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:$otelAlphaVersion")
        implementation("io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2:$otelAlphaVersion")
        implementation("io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0:$otelAlphaVersion")
    }

    implementation("io.micronaut.tracing:micronaut-tracing-opentelemetry-http")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
    implementation("io.opentelemetry:opentelemetry-extension-aws")
    implementation("io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2")
    implementation("io.opentelemetry.contrib:opentelemetry-aws-xray")

    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0")
}

```

reflect-json.config
```
[
  {
    "name": "io.opentelemetry.instrumentation.logback.v1_0.LoggingEventWrapper",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true,
    "condition": {
      "typeReachable": "io.opentelemetry.instrumentation.logback.v1_0.LoggingEventWrapper"
    }
  },
  {
    "name": "io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true,
    "condition": {
      "typeReachable": "io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender"
    }
  },
  {
    "name": "io.opentelemetry.instrumentation.logback.v1_0.internal.UnionMap",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true,
    "condition": {
      "typeReachable": "io.opentelemetry.instrumentation.logback.v1_0.internal.UnionMap"
    }
  },
  {
    "name": "io.opentelemetry.instrumentation.logback.v1_0.internal.UnionMap$ConcatenatedSet",
    "allDeclaredFields": true,
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true,
    "condition": {
      "typeReachable": "io.opentelemetry.instrumentation.logback.v1_0.internal.UnionMap$ConcatenatedSet"
    }
  }
]
```

### Environment Information

JDK Version: 11
GraalVM Version: 22.2.0

### Version

3.7.3

**Comment by altro3** [comment]
@driverpt Hi! Just use version 4.5.0 - https://mvnrepository.com/artifact/io.micronaut.tracing/micronaut-tracing-core/4.5.0

@graemerocher version 4.5.0 is lost on the releases page https://github.com/micronaut-projects/micronaut-tracing/releases :-(

**Comment by driverpt** [comment]
Is it possible to dynamically configure OTEL Version?

**Comment by altro3** [comment]
What do you mean? Change the version that is used in micronaut to your own? If yes, then only in theory. The reality is that the api changes with each version and there is no guarantee that the latest version of micronaut-tracing will work with any version of opentelemetry

**Comment by n0tl3ss** [comment]
Thanks for reporting this.

Micronaut Tracing is built and tested against a specific OpenTelemetry version line. OpenTelemetry instrumentation APIs change between releases, so overriding those dependencies in an application is not something this project can support generically.

Because of that, we should not try to make the module work with arbitrary user-selected OTEL versions. The supported path is to use the OTEL version line managed by the Micronaut Tracing release you depend on, and upgrade Micronaut Tracing itself when newer OTEL support is added here.

Closing this issue as not planned.
