### ISSUE TITLE
ClassCastException from TracingCorePublisher

### ISSUE THREAD

**Issue by David-16** [micronaut-projects/micronaut-tracing#41]
### Expected Behavior

Import background:  This is upgrading from Micronaut 2.x to 3.3.4.  We have RxJava2 leftovers from 2.x days, so I included the necessary `io.micronaut.rxjava2:micronaut-rxjava2-http-client` dependency as well as other 2.x -> 3.x changes

The attached test case should pass

### Actual Behaviour

With 3.3.4 I am seeing intermittent `ClassCastExceptions` when running a unit test.  If I run mvn test 10 times, it fails about 3 time with following:

```
java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
        at io.reactivex.Flowable.subscribe(Flowable.java:14927)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.rxjava2.instrument.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:57)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:157)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.onNext(FluxSwitchMap.java:236)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at io.micronaut.core.async.publisher.Publishers$JustPublisher$1.request(Publishers.java:563)
        at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:162)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.onSubscribe(FluxSwitchMap.java:201)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
        at io.micronaut.core.async.publisher.Publishers$JustPublisher.subscribe(Publishers.java:553)
        at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
        at reactor.core.publisher.Flux.blockFirst(Flux.java:2599)
        at io.micronaut.http.client.netty.DefaultHttpClient$3.exchange(DefaultHttpClient.java:612)
        at io.micronaut.http.client.BlockingHttpClient.exchange(BlockingHttpClient.java:77)
        at io.micronaut.http.client.BlockingHttpClient.exchange(BlockingHttpClient.java:91)
        at mypackage.mytest.ServerTests.testCreateAndDropDatabaseObjects(ServerTests.java:29)
        .... junit stuff ......
        .... maven stuff ......

        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Flux.blockFirst(Flux.java:2600)
                ... 73 more

Caused by: java.lang.ClassCastException: class io.micronaut.rxjava2.instrument.RxInstrumentedFlowableSubscriber cannot be cast to class reactor.core.CoreSubscriber (io.micronaut.rxjava2.instrument.RxInstrumentedFlowableSubscriber and reactor.core.CoreSubscriber are in unnamed module of loader 'app')
        at io.micronaut.tracing.instrument.util.TracingCorePublisher.doSubscribe(TracingCorePublisher.java:162)
        at io.micronaut.tracing.instrument.util.TracingPublisher.subscribe(TracingPublisher.java:193)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        ... 97 more
```

### Steps To Reproduce

Here is the test:
```
@MicronautTest
class ServerTests {
    @Client("http://${micronaut.server.host}:${micronaut.server.port}" + EcpBootstrapRestApi.BASE_URL + "/provision")
    @Inject HttpClient httpClient;

    @Test
    void testCreateAndDropDatabaseObjects() {
        // Test POST /provision
        // Given the database objects do not exist
        assertDatabaseObjectsDoNotExist();

        // When POST localhost:8080/v1/ecp/infra/provision is called
        final HttpResponse<Object> response = httpClient.toBlocking().exchange(HttpRequest.POST("", null));

        // Then the response SHOULD be HTTP/200
        assertEquals(HttpStatus.OK, response.getStatus());
    }
```

### Environment Information

openjdk 11.0.9.1 2020-11-04
Micronaut 3.3.4

### Version

3.3.4

**Comment by David-16** [comment]
Note the HTTP client is effectively calling localhost.  The Controller is running in the same JVM and its return type is `io.reactivex.Completable`

For what it is worth, I am able to set breakpoints when it happens

I suspect the issue is just that `TracingCorePublisher` is always assuming the incoming `Subscriber` is of type `CoreSubscriber` and that probably works if everyone uses Project Reactor, but we still have RxJava2 from the Micronaut 2.x days

I do not fully understand the intermittency of the issue, I suspect it is just a thread scheduling / race condition from having the client and server in the same JVM

Can you confirm if this is an incorrect assumption inside `TracingCorePublisher` or if this might be an issue with the test?

**Comment by graemerocher** [comment]
@n0tl3ss Please take a look at this one next

**Comment by n0tl3ss** [comment]
Hi @David-16, It would be nice if you can provide demo project because I have to reproduce it, but base on your explanation the environment is very special and I am not sure if I will be able to recreate it by myself.

**Comment by David-16** [comment]
I am not sure the environment is very special.  We have a `@Controller` running that returns an RxJava2 `Completable`

```
public interface EcpBootstrapRestApi {
    String BASE_URL = "/foo/bar/infra";

    @Post("/provision")
    Completable bootstrap();
}
```

We have a `@Client` in the same JVM (for unit testing) that calls the `@Controller` (see above)

As said, it does not reproduce reliably even then

`TracingCorePublisher` looks like it can only accept `CorePublisher` during construction, however, I do not think that necessarily implies it will only ever accept `CoreSubscriber` during subscription

`TracingCorePublisher` overrides `public void subscribe(CoreSubscriber<? super T> subscriber)` to make it seem like it only accepts `CoreSubscriber`, but it extends `TracingPublisher` and thus must still honor the underlying broader contract type of: `public void subscribe(Subscriber<? super T> actual)` (otherwise it would not correctly implement the interface method)

I think [`TracingCorePublisher#doSubscribe`](https://github.com/micronaut-projects/micronaut-tracing/blob/8a1a09094465506166db5c6c6774ff9bc61f0456/tracing-core/src/main/java/io/micronaut/tracing/instrument/util/TracingCorePublisher.java#L162) needs to do something similar to [`TracingPublisherUtils#createTracingPublisher`](https://github.com/micronaut-projects/micronaut-tracing/blob/8a1a09094465506166db5c6c6774ff9bc61f0456/tracing-core/src/main/java/io/micronaut/tracing/instrument/util/TracingPublisherUtils.java#L66) wherein it checks the type and calls one method or another

E.g.,
```
if (actual instanceof CoreSubscriber) {
    CoreSubscriber<? extends T> coreActual = (CoreSubscriber<? extends T>) actual;
    publisher.subscribe(new TracingCoreSubscriber(scopeManager, span, actual, finishOnClose, coreActual.currentContext()));
} else {
    publisher.subscribe(new TracingSubscriber(scopeManager, span, actual, finishOnClose));
}
```

**Comment by n0tl3ss** [comment]
@David-16 The thing that's bothering me is that I think you have mix of dependencies from Micronaut 3.x and Micronaut 2.x. I know that you are migrating project to newer version. The RxInstrumentedFlowableSubscriber class is only present in micronaut-runtime 2.x. I tried to reproduce problem with 3.x without any success. Probably it would be the best to switch all 2.x dependencies for 3.x ones.
